version: '3.5'

services:

  mongodb:
    
    container_name: mongodb
    
    image: "mongo:latest"

    volumes:
      - ~/docker_data/mongo/data:/data/db
    
    ports:
      - "27018:27017"

    restart: always

